services:
  mariadb:
    env_file: ".env"
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    env_file: ".env"
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always 
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
    - "8443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

volumes:
  mariadb_data:
  wordpress_data:
  