FROM debian:bullseye

RUN apt-get update \
	&& apt-get install -y mariadb-server \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

COPY ./tools/init.sh /init.sh

RUN chmod +x /init.sh

CMD ["/init.sh"]